### ISSUE TITLE
generator data

### ISSUE THREAD

**Issue by bringtree** [brightmart/multi-label_classification#1]
Hello, thank you for sharing the code with us.
When I read the readme, I meet some question.

For example. 
sentence A, label: [0,1,2]
sentence B, label: [1,2,3]

For label [0,3], sentence A and sentence B are not similar sentence pair.
For label [1,2], sentence A and sentence B are similar sentence pair.
When you generator data, Are sentence A and sentence B similar?

**Comment by brightmart** [comment]
no, not even the case.

i haven't met this kinds of problem.

our settings are like this: we have a sentence or paragraph, and labels are [0,1,2]. labels are associate with Chinese description. the question is how we generate more training data and use more information.

**Comment by bringtree** [comment]
Thanks.
AB belongs to the same class, and BC belongs to the same class, but the AC similarity is low. I think your approach may be to reduce this situation.
