### ISSUE TITLE
模型预测

### ISSUE THREAD

**Issue by Vincent131499** [brightmart/multi-label_classification#2]
Hi，你好，我在加载训练好的模型进行预测时，程序并不会输出任何值。
请问：在run_classifier_predict_online中BERT_BASE_DIR应该怎么设置呢？除了这个参数之外，在预测时，还有其他地方需要调整吗

**Comment by brightmart** [comment]
BERT_BASE_DIR是模型checkpoint的路径，需要这个路径下有词汇表和bert的配置文件。

**Comment by Vincent131499** [comment]
针对词汇表和bert配置文件这两个文件：
我理解的是，这个词汇表文件是需要在训练模型时自己手动保存；
而bert配置文件，就是谷歌开源的预训练模型中的bert_config.json文件。
不知道是否正确？

**Comment by brightmart** [comment]
词汇表(vocab.txt)、bert配置文件(bert_config.json)，这两个文件都和原生的bert是一模一样的，可以直接拿过来用。
